### ISSUE TITLE
Question about implementation of code

### ISSUE THREAD

**Issue by TinyTigerPan** [mhh0318/Cocktail#2]
Wonderful job, but I have a question about the implementation.
It can easily to find the implementation of 3.1 Generalized ControlNet with Controllable Normalisation is in `ccldm_cocktail.py`, but how about 3.2 Spatial Guidance Sampling.
Thanks a lot.

**Comment by mhh0318** [comment]
It is scattered and wrapped in files like mcldm.py, pwwccldm.py, etc. We are cleaning up the messy code, please give us time to provide a clean version.
